#!/bin/sh
# install files from source to dest
# sample file:
# bla /etc/bla
#end
while getopts r: arg ; do
    case $arg in
	r) dir_root="$OPTARG" ;;
    esac
done
if [ ! "$dir_root" ] ; then
    echo "Need dir root" >&2
    exit 1
fi

shift $(($OPTIND - 1 ))

if [ ! -f $1 ] ; then
    echo "Need input file" >&2
    exit 1
fi
file=$1
if [ ! $(dirname $file) = . ] && [ ! $(dirname $file) = .. ]   ; then
    dir_root=$PWD/$dir_root
    cd ${file##*/} # dirname
    file=${file%/*} # basename
fi
while read -r line  ; do
    case $line in
	^#*)
	    :
	    ;;
	*)
            source=$(echo ${line%\ *} | sed 's/ $//') # delete spaces
            target=$(echo ${line#*\ } | sed 's/ $//')
            mkdir -p "$dir_root"/"$(dirname $target)" 
            cp -a $source "$dir_root"/"$target"
            ;;
    esac
done < $file

